# Generated by Django 5.0.6 on 2024-06-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_listitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='name',
            new_name='content',
        ),
    ]
