# Generated by Django 5.0.6 on 2024-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0003_rename_name_listitem_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("personal", "Personal"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=10,
            ),
        ),
    ]
