# Generated by Django 5.0.6 on 2024-06-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='list_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
