# Generated by Django 5.0.6 on 2024-06-19 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0007_publisher_book"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Publisher",
        ),
    ]
